---
- name: Install flatpak
  apt:
    name: flatpak
    state: present
    update_cache: yes
  become: yes

- name: Install Gnome Software plugin for flatpak
  apt:
    name: gnome-software-plugin-flatpak
    state: present
    update_cache: yes
  become: yes