---
- name: Install flatpak
  apt:
    name: flatpak
    state: present
    update_cache: yes
    autoremove: yes
  become: yes

- name: Install Gnome Software plugin for flatpak
  apt:
    name: gnome-software-plugin-flatpak
    state: present
    update_cache: yes
    autoremove: yes
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'