---
- name: Install flatpak
  apt:
    name: flatpak
    state: present
  become: yes

- name: Install Gnome Software plugin for flatpak
  apt:
    name: gnome-software-plugin-flatpak
    allow-remove-essential: yes
    state: present
  become: yes